FROM adoptopenjdk:11-jre-hotspot-bionic
ADD target/managecurrencyconversionfactor-0.0.1-SNAPSHOT.jar managecurrencyconversionfactor.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-jar" , "managecurrencyconversionfactor.jar"]
